export const POST_ORDER_BY_SCORE = 'POST_ORDER_BY_SCORE'
export const POST_ORDER_BY_TIMESTAMP = 'POST_ORDER_BY_TIMESTAMP'

export const COMMENT_ORDER_BY_SOCRE = 'COMMENT_ORDER_BY_SCORE'
export const COMMENT_ORDER_BY_TIMESTAMP = 'COMMENT_ORDER_BY_TIMESTAMP'

export const ADD_POST = 'ADD_POST'
export const EDIT_POST = 'EDIT_POST'
export const DELETE_POST = 'DELETE_POST'
export const UP_VOTE_POST = 'UP_VOTE_POST'
export const DOWN_VOTE_POST = 'DOWN_VOTE_POST'

export const ADD_COMMENT = 'ADD_COMMENT'
export const EDIT_COMMENT = 'EDIT_COMMENT'
export const DELETE_COMMENT = 'DELETE_COMMENT'
export const UP_VOTE_COMMENT = 'UP_VOTE_COMMENT'
export const DOWN_VOTE_COMMENT = 'DOWN_VOTE_COMMENT'

export const ADD_CATEGORY = 'ADD_CATEGORY'